
---

  - name: Modul 1
    credits: 1
    id: B.1
    beschreibung: "k.A."
    univzid: "Automatisch"

  - name: Modul 2
    credits: 1
    id: B.2
    beschreibung: "k.A."
    univzid: "Automatisch"

  - name: Modul 3
    credits: 1
    id: B.3
    beschreibung: "k.A."
    univzid: "Automatisch"

  - name: Modul 4
    credits: 1
    id: B.4
    beschreibung: "k.A."
    univzid: "Automatisch"
        