---
name: "Version AM 34b vom 01.10.2009 (aktuelle Version)"
kurz: "PO SoSe 2009"
pfad: "po_ss_2009"
beschreibung: "Dies ist die erste Prüfungsordnung, die in dem neuen ModulManager ihre Verwendung findet."
datum: 2009-10-01
