
---
- name: standard
  semester1: B.Phy.101, B.Mat.011, B.Mat.012, B.Phy.605
  semester2: B.Phy.102, B.Phy.410, B.Phy.303, B.Phy.605.2
  semester3: B.Phy.103, B.Phy.304, B.Phy.201, B.Phy.410.2
  semester4: B.Phy.104, B.Phy.604, B.Phy.202
  semester5: B.Phy.402, B.Phy.203
  semester6: B.Phy.602, Bachelor

- name: Nanostrukturphysik
  semester1: B.Phy.101, B.Mat.011, B.Mat.012, B.Phy.605
  semester2: B.Phy.102, B.Phy.410, B.Phy.303, B.Phy.605.2
  semester3: B.Phy.103, B.Phy.304, B.Phy.201, B.Phy.410.2
  semester4: B.Phy.104, B.Phy.604, B.Phy.202
  semester5: B.Phy.402, B.Phy.203, B.Phy.403, B.Phy.503
  semester6: B.Phy.602, Bachelor

- name: Physikinformatik
  semester1: B.Phy.101, B.Mat.011, B.Mat.012, B.Phy.605
  semester2: B.Phy.102, B.Phy.410, B.Phy.303, B.Phy.605.2
  semester3: B.Phy.103, B.Phy.304, B.Phy.201, B.Phy.510, B.Phy.410.2
  semester4: B.Phy.104, B.Phy.604, B.Phy.202, B.Phy.511
  semester5: B.Phy.402, B.Phy.203, B.Phy.404
  semester6: B.Phy.602, Bachelor

- name: Astro- und Geophysik
  semester1: B.Phy.101, B.Mat.011, B.Mat.012, B.Phy.605
  semester2: B.Phy.102, B.Phy.410, B.Phy.303, B.Phy.605.2
  semester3: B.Phy.103, B.Phy.304, B.Phy.201, B.Phy.410.2
  semester4: B.Phy.104, B.Phy.604, B.Phy.202, B.Phy.501
  semester5: B.Phy.402, B.Phy.203, B.Phy.405
  semester6: B.Phy.602, Bachelor

- name: Biophysik und Physik komplexer Systeme
  semester1: B.Phy.101, B.Mat.011, B.Mat.012, B.Phy.605
  semester2: B.Phy.102, B.Phy.410, B.Phy.303, B.Phy.605.2
  semester3: B.Phy.103, B.Phy.304, B.Phy.201, B.Phy.410.2
  semester4: B.Phy.104, B.Phy.604, B.Phy.202, B.Phy.502
  semester5: B.Phy.402, B.Phy.203, B.Phy.406
  semester6: B.Phy.602, Bachelor

- name: Festkörper- und Materialphysik
  semester1: B.Phy.101, B.Mat.011, B.Mat.012, B.Phy.605
  semester2: B.Phy.102, B.Phy.410, B.Phy.303, B.Phy.605.2
  semester3: B.Phy.103, B.Phy.304, B.Phy.201, B.Phy.410.2
  semester4: B.Phy.104, B.Phy.604, B.Phy.202
  semester5: B.Phy.402, B.Phy.203, B.Phy.407, B.Phy.503
  semester6: B.Phy.602, Bachelor

- name: Kern- und Teilchenphysik
  semester1: B.Phy.101, B.Mat.011, B.Mat.012, B.Phy.605
  semester2: B.Phy.102, B.Phy.410, B.Phy.303, B.Phy.605.2
  semester3: B.Phy.103, B.Phy.304, B.Phy.201, B.Phy.410.2
  semester4: B.Phy.104, B.Phy.604, B.Phy.202
  semester5: B.Phy.402, B.Phy.203, B.Phy.408, B.Phy.504
  semester6: B.Phy.602, Bachelor