class ClearRules < ActiveRecord::Migration
  def self.up
    Rule.all.each do |r|
      r.destroy
    end
  end

  def self.down
    CreditRule.create :name => "Pflichtmodule",
      :count => 102,
      :relation => "min"
    CreditRule.create :name => "Grundkurs11",
      :count => 54,
      :relation => "min"
    CreditRule.create :name => "Praktika11",
      :count => 15,
      :relation => "min"
    CreditRule.create :name => "Mathematik11",
      :count => 33,
      :relation => "min"
    CreditRule.create :name => "Spezialisierungsbereich",
      :count => 30,
      :relation => "min"
    CreditRule.create :name => "Spezialisierungspraktikum11",
      :count => 6,
      :relation => "min"
    CreditRule.create :name => "Einführungen11",
      :count => 12,
      :relation => "min"
    CreditRule.create :name => "Spezielle Themen",
      :count => 12,
      :relation => "min"
    CreditRule.create :name => "Profilierungsbereich",
      :count => 18,
      :relation => "min"
    CreditRule.create :name => "MathNat",
      :count => 6,
      :relation => "min"
    CreditRule.create :name => "NichtPhysikalisch",
      :count => 12,
      :relation => "min"
    CreditRule.create :name => "NanoGes",
      :count => 30,
      :relation => "min"
    CreditRule.create :name => "Nano11",
      :count => 12,
      :relation => "min"
    CreditRule.create :name => "Nano21",
      :count => 12,
      :relation => "min"
    CreditRule.create :name => "Nano31",
      :count => 6,
      :relation => "min"
    CreditRule.create :name => "InfGes",
      :count => 30,
      :relation => "min"
    CreditRule.create :name => "Inf11",
      :count => 18,
      :relation => "min"
    CreditRule.create :name => "Inf21",
      :count => 6,
      :relation => "min"
    CreditRule.create :name => "AstroGes",
      :count => 30,
      :relation => "min"
    CreditRule.create :name => "Astro11",
      :count => 12,
      :relation => "min"
    CreditRule.create :name => "Astro21",
      :count => 12,
      :relation => "min"
    CreditRule.create :name => "Astro31",
      :count => 6,
      :relation => "min"
    CreditRule.create :name => "BioGes",
      :count => 30,
      :relation => "min"
    CreditRule.create :name => "Bio11",
      :count => 12,
      :relation => "min"
    CreditRule.create :name => "Bio21",
      :count => 12,
      :relation => "min"
    CreditRule.create :name => "Bio31",
      :count => 6,
      :relation => "min"
    CreditRule.create :name => "MatGes",
      :count => 30,
      :relation => "min"
    CreditRule.create :name => "Mat11",
      :count => 12,
      :relation => "min"
    CreditRule.create :name => "Mat21",
      :count => 12,
      :relation => "min"
    CreditRule.create :name => "Mat31",
      :count => 6,
      :relation => "min"
    CreditRule.create :name => "KernGes",
      :count => 30,
      :relation => "min"
    CreditRule.create :name => "Kern11",
      :count => 12,
      :relation => "min"
    CreditRule.create :name => "Kern21",
      :count => 12,
      :relation => "min"
    CreditRule.create :name => "Kern31",
      :count => 6,
      :relation => "min"
    CreditRule.create :name => "Schlüsselkompetenzen",
      :count => 18,
      :relation => "min"

    ModuleRule.create :name => "Grundkurs12",
      :count => 7,
      :relation => "min"
    ModuleRule.create :name => "Praktika12",
      :count => 2,
      :relation => "min"
    ModuleRule.create :name => "Mathematik12",
      :count => 4,
      :relation => "min"
    ModuleRule.create :name => "Spezialisierungspraktikum12",
      :count => 1,
      :relation => "min"
    ModuleRule.create :name => "Einführungen12",
      :count => 2,
      :relation => "min"
    ModuleRule.create :name => "Nano12",
      :count => 2,
      :relation => "min"
    ModuleRule.create :name => "Nano22",
      :count => 2,
      :relation => "min"
    ModuleRule.create :name => "Nano32",
      :count => 1,
      :relation => "min"
    ModuleRule.create :name => "Inf12",
      :count => 3,
      :relation => "min"
    ModuleRule.create :name => "Inf22",
      :count => 1,
      :relation => "min"
    ModuleRule.create :name => "Astro12",
      :count => 2,
      :relation => "min"
    ModuleRule.create :name => "Astro22",
      :count => 2,
      :relation => "min"
    ModuleRule.create :name => "Astro32",
      :count => 1,
      :relation => "min"
    ModuleRule.create :name => "Bio12",
      :count => 2,
      :relation => "min"
    ModuleRule.create :name => "Bio22",
      :count => 2,
      :relation => "min"
    ModuleRule.create :name => "Bio32",
      :count => 1,
      :relation => "min"
    ModuleRule.create :name => "Mat12",
      :count => 2,
      :relation => "min"
    ModuleRule.create :name => "Mat22",
      :count => 2,
      :relation => "min"
    ModuleRule.create :name => "Mat32",
      :count => 1,
      :relation => "min"
    ModuleRule.create :name => "Kern12",
      :count => 2,
      :relation => "min"
    ModuleRule.create :name => "Kern22",
      :count => 2,
      :relation => "min"
    ModuleRule.create :name => "Kern32",
      :count => 1,
      :relation => "min"
    ModuleRule.create :name => "Schlüsselkompetenzen12",
      :count => 3,
      :relation => "min"
  end
end
